services:
  - type: web
    name: scheduler-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
